ALTER TABLE `t_company_stock`
ADD COLUMN `dtzf` VARCHAR(128) DEFAULT NULL COMMENT '当天涨幅%' AFTER `market_time`,
ADD COLUMN `dtcjl` VARCHAR(128) DEFAULT NULL COMMENT '当天成交量（手）' AFTER `dtzf`,
ADD COLUMN `dtcjje` decimal(25,5) DEFAULT NULL COMMENT '当天成交金额（元）' AFTER `dtcjl`,
ADD COLUMN `dthsl` VARCHAR(128) DEFAULT NULL COMMENT '当天换手率%' AFTER `dtcjje`,
ADD COLUMN `lb` VARCHAR(128) DEFAULT NULL COMMENT '量比' AFTER `dthsl`,
ADD COLUMN `syl` VARCHAR(128) DEFAULT NULL COMMENT '市盈率%' AFTER `lb`;

ALTER TABLE `t_company_price_record`
ADD COLUMN `dtzf` VARCHAR(128) DEFAULT NULL COMMENT '当天涨幅%' AFTER `lowest_price`,
ADD COLUMN `dtcjl` VARCHAR(128) DEFAULT NULL COMMENT '当天成交量（手）' AFTER `dtzf`,
ADD COLUMN `dtcjje` decimal(25,5) DEFAULT NULL COMMENT '当天成交金额（元）' AFTER `dtcjl`,
ADD COLUMN `dthsl` VARCHAR(128) DEFAULT NULL COMMENT '当天换手率%' AFTER `dtcjje`,
ADD COLUMN `lb` VARCHAR(128) DEFAULT NULL COMMENT '量比' AFTER `dthsl`,
ADD COLUMN `syl` VARCHAR(128) DEFAULT NULL COMMENT '市盈率%' AFTER `lb`;